# Generated by Django 5.1.1 on 2024-09-26 02:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_model_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("99d7d6a4-1ef6-4c31-a2d4-f05f69878d9c"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
