# Generated by Django 5.1.1 on 2024-09-29 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_model_app", "0002_alter_stockmodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="change",
            field=models.DecimalField(decimal_places=10, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="close_price",
            field=models.DecimalField(decimal_places=10, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("336c3508-b203-4c1c-92f9-62c81c321723"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="market_cap",
            field=models.DecimalField(decimal_places=10, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="sector",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="volume",
            field=models.DecimalField(decimal_places=10, max_digits=21, null=True),
        ),
    ]
