# Generated by Django 5.1.1 on 2024-09-29 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stock_model_app",
            "0003_alter_stockmodel_change_alter_stockmodel_close_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("4a53e50c-94c3-49c0-b115-e9e0520a8d7a"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
