# Generated by Django 5.1.1 on 2024-09-29 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_model_app", "0004_alter_stockmodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="change",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=21),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="close_price",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=21),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("8ec4e233-6a2a-44bf-adee-cfb156104708"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="market_cap",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=21),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="volume",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=21),
        ),
    ]
