# Generated by Django 5.1.1 on 2024-09-29 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stock_model_app",
            "0005_alter_stockmodel_change_alter_stockmodel_close_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="change",
            field=models.DecimalField(decimal_places=24, default=0.0, max_digits=38),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="close_price",
            field=models.DecimalField(decimal_places=24, default=0.0, max_digits=38),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("aae9ff89-59a1-4a9c-b28e-9265168f664b"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="market_cap",
            field=models.DecimalField(decimal_places=24, default=0.0, max_digits=38),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="volume",
            field=models.DecimalField(decimal_places=24, default=0.0, max_digits=38),
        ),
    ]
