# Generated by Django 5.1.1 on 2024-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stock_model_app",
            "0006_alter_stockmodel_change_alter_stockmodel_close_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="id",
            field=models.UUIDField(
                db_index=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
