# Generated by Django 5.1.1 on 2024-09-30 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_model_app", "0007_alter_stockmodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 30, 1, 55, 1, 144611, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterModelTable(
            name="stockmodel",
            table="tb_stock_info",
        ),
    ]
