# Generated by Django 5.1.1 on 2024-09-30 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_model_app", "0008_stockmodel_created_at_alter_stockmodel_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 30, 2, 20, 48, 394838, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
