# Generated by Django 5.1.1 on 2024-09-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_model_app", "0010_alter_stockmodel_created_at_alter_stockmodel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
